---
# tasks file for dnsmasq
- name: copy systemd unit file
  ansible.builtin.template:
    src: systemd/dnsmasq.service.j2
    dest: /etc/systemd/system/dnsmasq.service
  notify: dnsmasq - restart service

- name: create dnsmasq lease directory
  ansible.builtin.file:
    path: /var/lib/dnsmasq/
    state: directory

- name: copy dnasmasq conf
  ansible.builtin.copy:
    src: dnsmasq/dnsmasq.conf
    dest: /etc/dnsmasq.conf
  notify: dnsmasq - restart service

- name: ensure dnsmasq is running
  ansible.builtin.systemd:
    name: dnsmasq
    daemon_reload: yes
    state: started

